name: Проверка
on: [push]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8
  tests:
    name: Test for Rest Api
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install pytest==7.4.2
        pip install requests
    - name: Pytest
      run: pytest test_rest.py
