name: Проверка
on: [push]
jobs:
  linter:
    name: Linter
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.12
    - name: Install requirements
      run: |
        python -m pip install --upgrade pip
        pip install flake8==3.9.0 wemake-python-styleguide==0.15.3 bandit==1.7.2
    - name: Flake8
      run: flake8
  container-job:
    name: Test for Rest Api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.12
      - name: Start postgres container
        run: |
          docker run -d --name movieHub -p 5525:5432 \
              -v $HOME/postgresql/movieHub/:/var/lib/postgresql/movieHub \
              -e POSTGRES_PASSWORD=test \
              -e POSTGRES_USER=test \
              -e POSTGRES_DB=test \
              postgres
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          echo "POSTGRES_PORT=5525" >> .env
          echo "POSTGRES_USER=test" >> .env
          echo "POSTGRES_PASSWORD=test" >> .env
          echo "POSTGRES_DB=test" >> .env
          echo "POSTGRES_HOST=127.0.0.1" >> .env
      - name: qwe
        run: python3 main.py
      - name: Pytest
        run: pytest test_rest.py